name: OldSchool-CICD

on:
  push:
    branches:
      - "*"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v3

      - name: Docker-Version pr√ºfen
        run: docker --version

      - name: Docker-Image bauen
        run: |
          docker build -t oldschool-test-image .

      - name: Container starten & testen
        run: |
          output=$(docker run --rm oldschool-test-image)
          echo "$output"
          if [ "$output" != "OldSchool GmbH - automatischer Build erfolgreich!" (Daniel S.)]; then
            echo "Test fehlgeschlagen :(!"
            exit 1
          fi

